{
 "title": "Air Quality",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Current", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "value": "time" },
      { "value": "temperature" }
     ],
     "limit": "1",
     "orderBy": "time DESC",
     "queryText": "SELECT time,temperature FROM sen55 ORDER BY time DESC LIMIT 1",
     "table": "sen55",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "value": "time" },
      { "value": "humidity" }
     ],
     "limit": "1",
     "orderBy": "time DESC",
     "queryText": "SELECT time,humidity FROM sen55 ORDER BY time DESC LIMIT 1",
     "table": "sen55",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "PM1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "value": "time" },
      { "value": "pm_1m_weight_concentration" }
     ],
     "limit": "1",
     "orderBy": "time DESC",
     "queryText": "SELECT time,pm_1m_weight_concentration FROM sen55 ORDER BY time DESC LIMIT 1",
     "table": "sen55",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "PM2.5",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "value": "time" },
      { "value": "pm_25m_weight_concentration" }
     ],
     "limit": "1",
     "orderBy": "time DESC",
     "queryText": "SELECT time,pm_25m_weight_concentration FROM sen55 ORDER BY time DESC LIMIT 1",
     "table": "sen55",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "PM4",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "value": "time" },
      { "value": "pm_4m_weight_concentration" }
     ],
     "limit": "1",
     "orderBy": "time DESC",
     "queryText": "SELECT time,pm_4m_weight_concentration FROM sen55 ORDER BY time DESC LIMIT 1",
     "table": "sen55",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "PM10",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "value": "time" },
      { "value": "pm_10m_weight_concentration" }
     ],
     "orderBy": "time",
     "queryText": "SELECT time,pm_10m_weight_concentration FROM sen55 WHERE $__timeRange(time) ORDER BY time",
     "table": "sen55",
     "wheres": [
      { "value": "$__timeRange(time)" }
     ]
    }
   ]
  },
  {
   "title": "VOC",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "value": "time" },
      { "value": "voc" }
     ],
     "limit": "1",
     "orderBy": "time DESC",
     "queryText": "SELECT time,voc FROM sen55 ORDER BY time DESC LIMIT 1",
     "table": "sen55",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "NOx",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "value": "time" },
      { "value": "nox" }
     ],
     "limit": "1",
     "orderBy": "time DESC",
     "queryText": "SELECT time,nox FROM sen55 ORDER BY time DESC LIMIT 1",
     "table": "sen55",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  { "title": "Historical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "columns": [
      { "value": "time" },
      { "value": "temperature" }
     ],
     "orderBy": "time",
     "queryText": "SELECT time,temperature FROM sen55 WHERE $__timeRange(time) ORDER BY time",
     "table": "sen55",
     "wheres": [
      { "value": "$__timeRange(time)" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "columns": [
      { "value": "time" },
      { "value": "humidity" }
     ],
     "orderBy": "time",
     "queryText": "SELECT time,humidity FROM sen55 WHERE $__timeRange(time) ORDER BY time",
     "table": "sen55",
     "wheres": [
      { "value": "$__timeRange(time)" }
     ]
    }
   ]
  },
  {
   "title": "Particulate Matter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "columns": [
      { "value": "time" },
      { "value": "pm_1m_weight_concentration" },
      { "value": "pm_25m_weight_concentration" },
      { "value": "pm_4m_weight_concentration" },
      { "value": "pm_10m_weight_concentration" }
     ],
     "orderBy": "time",
     "queryText": "SELECT time,pm_1m_weight_concentration,pm_25m_weight_concentration,pm_4m_weight_concentration,pm_10m_weight_concentration FROM sen55 WHERE $__timeRange(time) ORDER BY time",
     "table": "sen55",
     "wheres": [
      { "value": "$__timeRange(time)" }
     ]
    }
   ]
  },
  {
   "title": "Volatile Organic Compounds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "columns": [
      { "value": "time" },
      { "value": "voc" }
     ],
     "orderBy": "time",
     "queryText": "SELECT time,voc FROM sen55 ORDER BY time",
     "table": "sen55",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Nitrogen Oxides",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "columns": [
      { "value": "time" },
      { "value": "nox" }
     ],
     "orderBy": "time",
     "queryText": "SELECT time,nox FROM sen55 ORDER BY time",
     "table": "sen55",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  }
 ]
}